=== cagov/Cron/common/SQL/CDTCDPH_VACCINE/vaccines_by_race_ethnicity/schema/input/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "$id": "https://raw.githubusercontent.com/cagov/Cron/master/common/SQL/CDTCDPH_VACCINE/vaccines_by_race_ethnicity/schema/input/schema.json",
    "type": "array",
    "uniqueItems": true,
    "items": {
      "type": "object",
      "required": [
        "LATEST_ADMIN_DATE",
        "REGION",
        "CATEGORY",
        "METRIC_VALUE"
      ],
      "additionalProperties": false,
      "properties": {
        "LATEST_ADMIN_DATE": {
          "$ref": "#/definitions/date-YYYY-MM-DD"
        },
        "REGION": {
          "type": "string",
          "$ref": "#/definitions/region-california-counties"
        },
        "CATEGORY": {
          "type": "string",
          "type": "string",
          "enum": [
            "American Indian or Alaska Native",
            "Asian",
            "Black",
            "Latino",
            "Multiracial",
            "Native Hawaiian and other Pacific Islander",
            "Other",
            "Unknown",
            "White"
          ]
        },
        "METRIC_VALUE": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      }
    },
    "definitions": {
      "date-YYYY-MM-DD": {
        "type": "string",
        "pattern": "^\\d{4}-(?:0[0-9]{1}|1[0-2]{1})-(3[01]|0[1-9]|[12][0-9])$"
      },
      "categories-race-and-ethnicity": {
        "type": "string",
        "enum": [  
          "American Indian or Alaska Native",
          "Asian",
          "Black",
          "Latino",
          "Multi-Race",
          "Native Hawaiian and other Pacific Islander",
          "Other",
          "White"
        ]
      },
      "region-california-counties": {
        "type": "string",
        "minLength": 2,
        "maxLength": 60,
        "enum": [
          "Alameda",
          "Alpine",
          "Amador",
          "Butte",
          "Calveras",
          "Colusa",
          "Contra Costa",
          "Del Norte",
          "El Dorado",
          "Fresno",
          "Glenn",
          "Humboldt",
          "Imperial",
          "Inyo",
          "Kern ",
          "Kings",
          "Lake",
          "Lassen",
          "Los Angeles",
          "Madera",
          "Marin",
          "Mariposa",
          "Mendocino",
          "Merced",
          "Modoc",
          "Mono",
          "Monterey",
          "Napa",
          "Nevada",
          "Orange",
          "Placer",
          "Plumas",
          "Riverside",
          "Sacramento",
          "San Benito",
          "San Bernardino",
          "San Diego",
          "San Francisco",
          "San Joaquin",
          "San Luis Obispo",
          "San Mateo",
          "Santa Barbara",
          "Santa Clara",
          "Santa Cruz",
          "Shasta",
          "Sierra",
          "Siskiyou",
          "Solano",
          "Sonoma",
          "Stanislaus",
          "Sutter",
          "Tehama",
          "Trinity",
          "Tulare",
          "Tuolumne",
          "Ventura",
          "Yolo",
          "Yuba"
        ]
      }
    }
  }

=== cagov/Cron/common/SQL/CDTCDPH_VACCINE/vaccines_by_race_ethnicity/tests/output/pass/sample.json
[
    {
      "LATEST_ADMIN_DATE": "2021-03-16",
      "REGION": "Alameda",
      "CATEGORY": "White",
      "METRIC_VALUE": 0.271586
    },
    {
      "LATEST_ADMIN_DATE": "2021-03-16",
      "REGION": "Alameda",
      "CATEGORY": "Asian",
      "METRIC_VALUE": 0.214152
    },
    {
      "LATEST_ADMIN_DATE": "2021-03-16",
      "REGION": "Alameda",
      "CATEGORY": "Unknown",
      "METRIC_VALUE": 0.140695
    },
    {
      "LATEST_ADMIN_DATE": "2021-03-16",
      "REGION": "Alameda",
      "CATEGORY": "Multiracial",
      "METRIC_VALUE": 0.114141
    }
]
